remote_theme: allejo/jekyll-docs-theme@v1.0.0

name: SBBTracker

project:
  version: 4.0.3
  download_url: https://github.com/SBBTracker/SBBTracker/releases/latest
  download_text: Download

license:
  software: GPL v3
  software_url: https://www.gnu.org/licenses/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/SBBTracker/SBBTracker
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/SBBTracker/SBBTracker
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/SBBTracker/SBBTracker
    - title: Issues
      icon: bug
      url: https://github.com/SBBTracker/SBBTracker/issues?state=open